#!/bin/bash

os=$(uname -s)

showUsage () {
    echo "This script creates an installer package for oma at 'path_to_installer'."
    echo "Usage: makeinstaller path_to_installer"
    exit 1
}

if [ $# -le 0 ]
then
    showUsage
fi

versionnr=`git describe`
instpath=$1/OMA.$versionnr
webpath=linneus78.ethz.ch:${DARWIN_BROWSER_SHARE}/standalone

mkdir -p $instpath/bin
mkdir -p $instpath/DB
mkdir -p $instpath/data

# clone darwin repo, stripe .git folder and copy lib to $instpath
git clone --depth 1 git@cbrg-git.ethz.ch:darwin
rm -rf darwin/lib/.git
mv darwin/lib $instpath/darwinlib
rm -rf darwin

# clone hog_bottom_up python repo
git clone --depth 1 ssh://gitolite@lab.dessimoz.org:2222/hog_bottom_up
cd hog_bottom_up; git log -n 1 --format=%H > bottom_up.version; cd ..
rm -rf hog_bottom_up/.git
mv hog_bottom_up $instpath/

# copy darwin binaries to $shortname/bin/${shortname}darwin
cp /home/darwin/v2/source/linux/darwin $instpath/bin/omadarwin.linux32
cp /home/darwin/v2/source/linux64_2.6.9/darwin $instpath/bin/omadarwin.linux64
cp /home/darwin/v2/source/macintel/darwin $instpath/bin/omadarwin.mac32
cp /home/darwin/v2/source/macintel64/darwin $instpath/bin/omadarwin.mac64

# copy oma library to $1/OMA$versionnr/lib
cp -r lib $instpath/

# copy OMA files to $1/OMA$versionnr
cp OMA.drw parameters.drw install.sh README.oma LICENSE release_notes.txt $instpath/
cp bin/oma bin/omadarwin bin/warthog $instpath/bin/

# create manual and copy files to $instpath
darwin < Manual/manual.drw
mkdir $instpath/Manual
cp Manual/manual.pdf $instpath/Manual/
cp Manual/manual.css $instpath/Manual/
cp Manual/manual.html $instpath/Manual/
cp release_notes.txt $instpath/Manual/

# copy toy example to $1/OMA$versionnr
cp -r ToyExample $instpath/ToyExample

# adjust for version number, remove devolopping functions
if [ $os = "Darwin" ]
then
    sed -i '' -e "s/\[VERSIONNR\]/$versionnr/g" $instpath/lib/splashscreen.txt \
 $instpath/install.sh $instpath/README.oma $instpath/bin/oma $instpath/hog_bottom_up/file_manager.py
    sed -i '' "/utildir/d" $instpath/lib/darwinit
    sed -i '' "s|datadirname.*|datadirname := libname.'/../data':|" $instpath/darwinlib/darwinit
else
    sed -i -e "s/\[VERSIONNR\]/$versionnr/g" $instpath/lib/splashscreen.txt \
 $instpath/install.sh $instpath/README.oma $instpath/bin/oma $instpath/hog_bottom_up/file_manager.py
    sed -i "/utildir/d" $instpath/lib/darwinit
    sed -i "s|datadirname.*|datadirname := libname.'/../data':|" $instpath/darwinlib/darwinit
fi

# create tarball
$(cd `dirname $instpath`; tar -cvzf `basename $instpath`.tgz `basename $instpath`)

# deploy webpage (html, css and tarball)
scp $(dirname $instpath)/$(basename $instpath).tgz ${webpath}
scp $(dirname $0)/Manual/manual.css ${webpath}
scp $(dirname $0)/Manual/manual.html ${webpath}/index.html
scp $(dirname $0)/release_notes.txt ${webpath}
