#!/bin/bash

showUsage () {
    echo "This script creates an installer package for oma at 'path_to_installer'."
    echo "Usage: makeinstaller path_to_installer"
    exit 1
}

if [ $# -le 0 ]
then
    showUsage
fi

versionnr=`git describe`
instpath=$1/OMA.$versionnr

mkdir -p $instpath/bin
mkdir -p $instpath/DB

# clone darwin repo, stripe .git folder and copy lib to $instpath
git clone --depth 1 git@cbrg-git.ethz.ch:darwin
rm -rf darwin/lib/.git
mv darwin/lib $instpath/darwinlib
rm -rf darwin

# copy darwin binaries to $shortname/bin/${shortname}darwin
cp /home/darwin/v2/source/linuxPIV/darwin $instpath/bin/omadarwin.linux32
cp /home/darwin/v2/source/linux64/darwin $instpath/bin/omadarwin.linux64
cp /home/darwin/v2/source/macintel/darwin $instpath/bin/omadarwin.mac32
cp /home/darwin/v2/source/BUILD-macintel64/darwin $instpath/bin/omadarwin.mac64

# copy oma library to $1/OMA$versionnr/lib
cp -r lib $instpath/

# copy OMA files to $1/OMA$versionnr
cp OMA.drw parameters.drw install.sh README.oma $instpath/
cp bin/oma bin/omadarwin $instpath/bin/

# copy toy example to $1/OMA$versionnr
cp -r ToyExample $instpath/ToyExample

# adjust for version number
sed -i '' -e "s/\[VERSIONNR\]/$versionnr/g" $instpath/lib/splashscreen.txt \
  $instpath/install.sh $instpath/README.oma $instpath/bin/oma

# create tarball
cd `dirname $instpath`; tar -cvzf `basename $instpath`.tgz `basename $instpath`
