#!/bin/bash

URL='http://localhost/oma.tgz'

if ! touch .omashorttest139867.txt 2>/dev/null
then
    echo "You need to have write access to the directory where you call this script.
Change into another directory (e.g. 'cd ~') and try again."
    exit
fi

rm .omashorttest139867.txt

echo "Downloading OMA..."
curl -s -o oma.tgz $URL
tar xvzf oma.tgz
rm oma.tgz

echo "Where do you want to install OMA?"
echo "For default (/usr/local), just press 'enter'."

read userinput

if [ "$userinput" = "" ]
then
    install_prefix='/usr/local'
else
    install_prefix=`dirname $userinput`/`basename $userinput`
fi

echo "Install in $install_prefix..."
oma/install.sh $install_prefix
echo "An example file 'parameters.drw' has been placed in $install_prefix/oma."
rm -rf oma
